name : "sample react app cicd"

on:
  push:
    branches: 
        - master
  pull_request:
    branches: 
        - main 
jobs:
  build-and-test: #name of the job
    runs-on: ubuntu-latest #specifies the type of machine to run the job on
    steps:

      - name : "Checkout code" #checks out the repository code
        uses : actions/checkout@v2
   
      - name: Set up Node.js #sets up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20' 
      
      - name : "check node version"
        run: node -v
        #checks out the repository code

      - name: Install dependencies #installs project dependencies
        run: npm install  

      - name : "list files"
        run: ls -la

      - name : "checak linting"
        run: npm run lint #runs linting checks

      - name: Run tests #runs tests
        run: npm test  

      - name : "build project"
        run: npm run build
        
      - name : "upload production ready build files"
        uses :  actions/upload-artifact@v4
        with :
          name : build
          path : /dist