name : "sample react app cicd"

on:
  push:
    branches: 
        - master
  pull_request:
    branches: 
        - main 
jobs:
  build-and-test: #name of the job
    runs-on: ubuntu-latest #specifies the type of machine to run the job on
    steps:
   
      - name: Set up Node.js #sets up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14' 
      
      - name : "check node version"
        run: node -v

      - name : "clone repository"
        uses: actions/checkout@v2 #checks out the repository code